spring.application.name=dialog
server.port=8081

spring.cloud.compatibility-verifier.enabled=false

services.backend.url=http://backend:8080

management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.observations.http.server.requests.enabled=true
# Этот параметр заставляет Micrometer пробрасывать контекст в логи (MDC)
management.tracing.propagation.type=w3c
# Для автоматического создания Span для каждого HTTP запроса
management.observations.key-values.enabled=true

logging.include-details=always
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

