spring.application.name=backend

# Primary datasource
spring.datasource.primary.url=jdbc:postgresql://pgmaster:5432/highload
spring.datasource.primary.schema=backend
spring.datasource.primary.username=backend
spring.datasource.primary.password=backend
spring.datasource.primary.driver-class-name=org.postgresql.Driver

# Replica datasource
spring.datasource.replica.url=jdbc:postgresql://pgslave1:5432/highload
spring.datasource.replica.schema=backend
spring.datasource.replica.username=backend
spring.datasource.replica.password=backend
spring.datasource.replica.driver-class-name=org.postgresql.Driver

# logging.level.org.jooq.tools.LoggerListener=DEBUG
# logging.level.com.zaxxer.hikari.HikariConfig=DEBUG
# logging.level.com.zaxxer.hikari=TRACE