spring.application.name=backend

# Primary datasource
spring.datasource.primary.url=jdbc:postgresql://citus_master:5432/postgres
spring.datasource.primary.schema=public
spring.datasource.primary.username=postgres
spring.datasource.primary.password=postgres
spring.datasource.primary.driver-class-name=org.postgresql.Driver

# Replica datasource
spring.datasource.replica.url=jdbc:postgresql://citus_master:5432/postgres
spring.datasource.replica.schema=public
spring.datasource.replica.username=postgres
spring.datasource.replica.password=postgres
spring.datasource.replica.driver-class-name=org.postgresql.Driver

#logging.level.org.jooq.tools.LoggerListener=DEBUG
#logging.level.com.zaxxer.hikari.HikariConfig=DEBUG
#logging.level.com.zaxxer.hikari=TRACE