{
 "title": "JMeter",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Кол-во пользователей",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(jmeter_threads{state=\"active\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Пропускная способность общая и по endpoints, кол-во fails",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by (endpoint) (\r\n  rate(\r\n    label_replace(\r\n      jmeter_success_ratio_success, \r\n      \"endpoint\", \"$1\", \"label\", \".*/(list|send)$\"\r\n    )[$__interval:]\r\n  )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (endpoint) (\r\n  label_replace(\r\n    rate(jmeter_success_ratio_failure[$__interval]),\r\n    \"endpoint\", \"$1\", \"label\", \".*/(list|send)$\"\r\n  )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (endpoint) (\r\n  label_replace(\r\n    rate(jmeter_success_ratio_total[$__interval]),\r\n    \"endpoint\", \"$1\", \"label\", \".*/(list|send)$\"\r\n  )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (endpoint) (\r\n  label_replace(\r\n    rate(jmeter_success_ratio_failure[$__interval]),\r\n    \"endpoint\", \"$1\", \"label\", \".*/(list|send)$\"\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время отклика по endpoints, перцентиль",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "avg by (endpoint) (\r\n  label_replace(\r\n    rate(jmeter_rt_summary_sum{code=~\"[1-5].*\"}[$__interval]),\r\n    \"endpoint\", \"$1\", \"label\", \".*/(list|send)$\"\r\n  )\r\n  /\r\n  label_replace(\r\n    (rate(jmeter_rt_summary_count{code=~\"[1-5].*\"}[$__interval]) > 0),\r\n    \"endpoint\", \"$1\", \"label\", \".*/(list|send)$\"\r\n  )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (quantile, endpoint) (\r\n  label_replace(\r\n    jmeter_rt_summary{code=\"200\"},\r\n    \"endpoint\", \"$1\", \"label\", \".*/(list|send)$\"\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}