spring.application.name=backend

# Datasource
spring.datasource.url=jdbc:postgresql://master:5432/postgres
spring.datasource.schema=public
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

#logging.level.org.jooq.tools.LoggerListener=DEBUG
#logging.level.com.zaxxer.hikari.HikariConfig=DEBUG
#logging.level.com.zaxxer.hikari=TRACE

# Генерировать traceId для 100% запросов
management.tracing.sampling.probability=1.0
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
